trigger:
  branches:
    include:
      - master
pr:
  branches:
    include:
      - master

variables:
  CAKE_SETTINGS_SHOWPROCESSCOMMANDLINE: true
  DOTNET_CLI_TELEMETRY_OPTOUT: true
  DOTNET_NOLOGO: true
  DOTNET_ROLL_FORWARD_ON_NO_CANDIDATE_FX: 2
  NUGET_PACKAGES: $(Pipeline.Workspace)/.nuget/packages

jobs:
  - job: Docker
    dependsOn: [Linux, Mac, Windows]
    pool:
      vmImage: ubuntu-latest
    container: dockfool/cake-docker:latest
    steps:
      - checkout: self
        displayName: Checkout source

      - task: Cache@2
        displayName: Cache packages
        inputs:
          path: $(NUGET_PACKAGES)
          key: $(Agent.OS)|nuget|.config/dotnet-tools.json,**/packages.lock.json
          restoreKeys: $(Agent.OS)|nuget

      - bash: dotnet tool restore && dotnet cake --verbosity=verbose --target=build
        displayName: Cake build

  - job: Linux
    pool:
      vmImage: ubuntu-latest
    steps:
      - checkout: self
        displayName: Checkout source

      - task: UseDotNet@2
        displayName: Install dotnet
        inputs:
          version: 5.0.100

      - task: Cache@2
        displayName: Cache packages
        inputs:
          path: $(NUGET_PACKAGES)
          key: $(Agent.OS)|nuget|.config/dotnet-tools.json,**/packages.lock.json
          restoreKeys: $(Agent.OS)|nuget

      - bash: dotnet tool restore && dotnet cake --verbosity=verbose --target=build
        displayName: Cake build

  - job: Mac
    pool:
      vmImage: macos-latest
    steps:
      - checkout: self
        displayName: Checkout source

      - task: UseDotNet@2
        displayName: Install dotnet
        inputs:
          version: 5.0.100

      - task: Cache@2
        displayName: Cache packages
        inputs:
          path: $(NUGET_PACKAGES)
          key: $(Agent.OS)|nuget|.config/dotnet-tools.json,**/packages.lock.json
          restoreKeys: $(Agent.OS)|nuget

      - bash: dotnet tool restore && dotnet cake --verbosity=verbose --target=build
        displayName: Cake build

  - job: Windows
    pool:
      vmImage: windows-latest
    steps:
      - checkout: self
        displayName: Checkout source

      - task: UseDotNet@2
        displayName: Install dotnet
        inputs:
          version: 5.0.100

      - task: Cache@2
        displayName: Cache packages
        inputs:
          path: $(NUGET_PACKAGES)
          key: $(Agent.OS)|nuget|.config/dotnet-tools.json,**/packages.lock.json
          restoreKeys: $(Agent.OS)|nuget

      - pwsh: dotnet tool restore && dotnet cake --verbosity=verbose --target=build
        displayName: Cake build
