trigger:
- master

variables:
  NUGET_PACKAGES: $(Pipeline.Workspace)/.nuget/packages

jobs:
- job: Docker
  dependsOn: [Linux, Mac, Windows]
  pool:
    vmImage: ubuntu-latest
  container: dockfool/cake-docker:latest
  steps:
  - checkout: self
    displayName: Checkout source

  - task: Cache@2
    inputs:
      path: $(NUGET_PACKAGES)
      key: $(Agent.OS)|nuget|**/packages.lock.json
      restoreKeys: |
        $(Agent.OS)|nuget
    displayName: Cache packages

  - bash: cake --bootstrap && cake --verbosity=verbose --ispublisher=true
    env:
      NUGET_API_KEY: $(NUGET_API_KEY)
      NUGET_SOURCE: $(NUGET_SOURCE)
    displayName: Cake build

- job: Linux
  pool:
    vmImage: ubuntu-latest
  steps:
  - checkout: self
    displayName: Checkout source

  - task: DotNetCoreInstaller@1
    inputs:
      version: 3.1.100
    displayName: Install .NET Core SDK

  - task: Cache@2
    inputs:
      path: $(NUGET_PACKAGES)
      key: $(Agent.OS)|nuget|**/packages.lock.json
      restoreKeys: |
        $(Agent.OS)|nuget
    displayName: Cache packages

  - bash: ./cake.sh --verbosity=verbose
    env:
      DOTNET_ROLL_FORWARD_ON_NO_CANDIDATE_FX: 2
    displayName: Cake build

- job: Mac
  pool:
    vmImage: macos-latest
  steps:
  - checkout: self
    displayName: Checkout source

  - task: DotNetCoreInstaller@1
    inputs:
      version: 3.1.100
    displayName: Install .NET Core SDK

  - task: Cache@2
    inputs:
      path: $(NUGET_PACKAGES)
      key: $(Agent.OS)|nuget|**/packages.lock.json
      restoreKeys: |
        $(Agent.OS)|nuget
    displayName: Cache packages

  - bash: ./cake.sh --verbosity=verbose
    env:
      DOTNET_ROLL_FORWARD_ON_NO_CANDIDATE_FX: 2
    displayName: Cake build

- job: Windows
  pool:
    vmImage: windows-latest
  steps:
  - checkout: self
    displayName: Checkout source

  - task: DotNetCoreInstaller@1
    inputs:
      version: 3.1.100
    displayName: Install .NET Core SDK

  - task: Cache@2
    inputs:
      path: $(NUGET_PACKAGES)
      key: $(Agent.OS)|nuget|**/packages.lock.json
      restoreKeys: |
        $(Agent.OS)|nuget
    displayName: Cache packages

  - powershell: ./cake.ps1 --verbosity=verbose
    env:
      DOTNET_ROLL_FORWARD_ON_NO_CANDIDATE_FX: 2
    displayName: Cake build
