workflow:
  rules:
    - if: '$CI_COMMIT_BRANCH || $CI_MERGE_REQUEST_TARGET_BRANCH_NAME == "master"'
    - when: never

variables:
  CAKE_SETTINGS_SHOWPROCESSCOMMANDLINE: "true"
  DOTNET_CLI_TELEMETRY_OPTOUT: "true"
  DOTNET_ROLL_FORWARD_ON_NO_CANDIDATE_FX: 2
  DOTNET_SKIP_FIRST_TIME_EXPERIENCE: "true"
  GIT_DEPTH: 0
  NUGET_PACKAGES: $CI_PROJECT_DIR/.nuget/packages

stages: [ Build ]

Docker:
  stage: Build
#   tags: [ ubuntu-latest ]
  image: dockfool/cake-docker:latest
  cache:
    paths: [ $NUGET_PACKAGES ]
    key:
      prefix: nuget
      files: [ packages.lock.json ]
  script:
    - dotnet tool restore && dotnet cake --bootstrap --verbosity=verbose && dotnet cake --verbosity=verbose --target=build

# Linux:
#   stage: Build
#   tags: [ ubuntu-latest ]
#   cache:
#     paths: [ $NUGET_PACKAGES ]
#     key:
#       prefix: nuget
#       files: [ packages.lock.json ]
#   script:
#     - dotnet tool restore && dotnet cake --bootstrap --verbosity=verbose && dotnet cake --verbosity=verbose --target=build

# Mac:
#   stage: Build
#   tags: [ macos-latest ]
#   cache:
#     paths: [ $NUGET_PACKAGES ]
#     key:
#       prefix: nuget
#       files: [ packages.lock.json ]
#   script:
#     - dotnet tool restore && dotnet cake --bootstrap --verbosity=verbose && dotnet cake --verbosity=verbose --target=build

# Windows:
#   stage: Build
#   tags: [ windows-latest ]
#   cache:
#     paths: [ $NUGET_PACKAGES ]
#     key:
#       prefix: nuget
#       files: [ packages.lock.json ]
#   script:
#     - dotnet tool restore ; dotnet cake --bootstrap --verbosity=verbose ; dotnet cake --verbosity=verbose --target=build
