workflow:
  rules:
    - if: '$CI_COMMIT_BRANCH && $CI_COMMIT_BRANCH !~ /^dependabot/'
    - if: '$CI_MERGE_REQUEST_TARGET_BRANCH_NAME == "master"'
    - when: never

variables:
  CAKE_SETTINGS_SHOWPROCESSCOMMANDLINE: "true"
  DOTNET_CLI_TELEMETRY_OPTOUT: "true"
  DOTNET_NOLOGO: "true"
  DOTNET_ROLL_FORWARD_ON_NO_CANDIDATE_FX: 2
  GIT_DEPTH: 0
  NUGET_PACKAGES: $CI_PROJECT_DIR/.nuget/packages

stages: [ Build ]

Docker:
  stage: Build
  tags: [ shared, linux, docker ]
  image: dockfool/cake-docker:latest
  cache:
    paths: [ $NUGET_PACKAGES ]
    key:
      prefix: linux-nuget
      files: [ packages.lock.json ]
  script:
    - dotnet tool restore && dotnet cake --bootstrap --verbosity=verbose && dotnet cake --verbosity=verbose --target=build

# Linux:
#   stage: Build
#   tags: [ shared, linux ]
#   cache:
#     paths: [ $NUGET_PACKAGES ]
#     key:
#       prefix: linux-nuget
#       files: [ packages.lock.json ]
#   script:
#     - curl -fsSL https://dot.net/v1/dotnet-install.sh | bash -s -- --version 3.1.301
#     - export DOTNET_ROOT=$HOME/.dotnet && export PATH=$DOTNET_ROOT:$PATH
#     - dotnet tool restore && dotnet cake --bootstrap --verbosity=verbose && dotnet cake --verbosity=verbose --target=build

# Mac:
#   stage: Build
#   tags: [ shared, macos ]
#   cache:
#     paths: [ $NUGET_PACKAGES ]
#     key:
#       prefix: nuget
#       files: [ packages.lock.json ]
#   script:
#     - curl -fsSL https://dot.net/v1/dotnet-install.sh | bash -s -- --version 3.1.301
#     - export DOTNET_ROOT=$HOME/.dotnet && export PATH=$DOTNET_ROOT:$PATH
#     - dotnet tool restore && dotnet cake --bootstrap --verbosity=verbose && dotnet cake --verbosity=verbose --target=build

Windows:
  stage: Build
  tags: [ shared-windows, windows ]
  cache:
    paths: [ $NUGET_PACKAGES ]
    key:
      prefix: windows-nuget
      files: [ packages.lock.json ]
  script:
    - '&powershell -NoProfile -ExecutionPolicy Unrestricted -Command "&([scriptblock]::Create((Invoke-WebRequest -UseBasicParsing https://dot.net/v1/dotnet-install.ps1))) -Version 3.1.301"'
    - $env:DOTNET_ROOT="$env:LocalAppData\Microsoft\dotnet" ; $env:PATH="$env:DOTNET_ROOT;$env:PATH"
    - dotnet tool restore ; dotnet cake --bootstrap --verbosity=verbose ; dotnet cake --verbosity=verbose --target=build
