trigger:
- master

jobs:
- job: Docker
  dependsOn: [Linux, Mac, Windows]
  pool:
    vmImage: ubuntu-16.04
  container: dockfool/cake-docker:latest
  steps:
  - bash: cake --bootstrap && cake --verbosity=verbose --ispublisher=true
    env:
      NUGET_API_KEY: $(NUGET_API_KEY)
      NUGET_SOURCE: $(NUGET_SOURCE)
    displayName: Cake build

- job: Linux
  pool:
    vmImage: ubuntu-16.04
  steps:
  - task: DotNetCoreInstaller@1
    inputs:
      version: 2.2.402
    displayName: Install .NET Core SDK

  - bash: ./cake.sh --verbosity=verbose
    displayName: Cake build

- job: Mac
  pool:
    vmImage: macOS-10.14
  steps:
  - task: DotNetCoreInstaller@1
    inputs:
      version: 2.2.402
    displayName: Install .NET Core SDK

  - bash: ./cake.sh --verbosity=verbose
    displayName: Cake build

- job: Windows
  pool:
    vmImage: windows-2019
  steps:
  - task: DotNetCoreInstaller@1
    inputs:
      version: 2.2.402
    displayName: Install .NET Core SDK

  - powershell: ./cake.ps1 --verbosity=verbose
    displayName: Cake build
