trigger:
- master
- refs/tags/*

variables:
- group: Cake
- group: DotNet
- group: NuGet

jobs:
- job: Docker
  pool:
    vmImage: ubuntu-16.04
  container:
    image: cakebuild/cake:v0.32.1-2.1-sdk
  steps:
  - bash: cake --bootstrap && cake --configuration=$(Cake.Configuration) --verbosity=$(Cake.Verbosity)
    displayName: Cake build
    env:
      NUGET_API_KEY: $(NuGet.Api.Key)

- job: Linux
  pool:
    vmImage: ubuntu-16.04
  steps:
  - task: DotNetCoreInstaller@0
    displayName: Install .NET Core SDK
    inputs:
      version: $(DotNet.Sdk.Version)

  - bash: ./cake.sh --configuration=$(Cake.Configuration) --verbosity=$(Cake.Verbosity)
    displayName: Cake build
    env:
      NUGET_API_KEY: $(NuGet.Api.Key)

- job: Mac
  pool:
    vmImage: macos-10.13
  steps:
  - task: DotNetCoreInstaller@0
    displayName: Install .NET Core SDK
    inputs:
      version: $(DotNet.Sdk.Version)

  - bash: ./cake.sh --configuration=$(Cake.Configuration) --verbosity=$(Cake.Verbosity)
    displayName: Cake build
    env:
      NUGET_API_KEY: $(NuGet.Api.Key)

- job: Windows
  pool:
    vmImage: vs2017-win2016
  steps:
  - task: DotNetCoreInstaller@0
    displayName: Install .NET Core SDK
    inputs:
      version: $(DotNet.Sdk.Version)

  - powershell: ./cake.ps1 -configuration $(Cake.Configuration) -verbosity $(Cake.Verbosity)
    displayName: Cake build
    env:
      NUGET_API_KEY: $(NuGet.Api.Key)
