name: Build
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  Docker:
    needs: [ Linux, Mac, Windows ]
    runs-on: ubuntu-latest
    container: dockfool/cake-docker:latest
    steps:
    - name: Checkout source
      uses: actions/checkout@v1

    - name: Cake build
      run: cake --bootstrap && cake --verbosity=verbose
      env:
        NUGET_API_KEY: ${{ secrets.NUGET_API_KEY }}
        NUGET_SOURCE: ${{ secrets.NUGET_SOURCE }}

  Linux:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout source
      uses: actions/checkout@v1

    - name: Install .NET Core SDK
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 3.0.100

    - name: Cake build
      run: ./cake.sh --verbosity=verbose
      env:
        DOTNET_ROLL_FORWARD_ON_NO_CANDIDATE_FX: 2

  Mac:
    runs-on: macos-latest
    steps:
    - name: Checkout source
      uses: actions/checkout@v1

    - name: Install .NET Core SDK
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 3.0.100

    - name: Cake build
      run: ./cake.sh --verbosity=verbose
      env:
        DOTNET_ROLL_FORWARD_ON_NO_CANDIDATE_FX: 2

  Windows:
    runs-on: windows-latest
    steps:
    - name: Checkout source
      uses: actions/checkout@v1

    - name: Install .NET Core SDK
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 3.0.100

    - name: Cake build
      shell: powershell
      run: ./cake.ps1 --verbosity=verbose
      env:
        DOTNET_ROLL_FORWARD_ON_NO_CANDIDATE_FX: 2
