name: Build
on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master
  workflow_dispatch:

env:
  CAKE_SETTINGS_SHOWPROCESSCOMMANDLINE: true
  DOTNET_CLI_TELEMETRY_OPTOUT: true
  DOTNET_NOLOGO: true
  DOTNET_ROLL_FORWARD: Major
  NUGET_API_KEY: ${{ secrets.NUGET_API_KEY }}
  NUGET_PACKAGES: ${{ github.workspace }}/.nuget/packages

jobs:
  Docker:
    needs: [ Linux, Mac, Windows ]
    runs-on: ubuntu-latest
    container: dockfool/cake-docker:latest
    steps:
      - name: Checkout source
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Cache packages
        uses: actions/cache@v2.1.5
        with:
          path: ${{ env.NUGET_PACKAGES }}
          key: ${{ runner.os }}-nuget-${{ hashFiles('.config/dotnet-tools.json', '**/packages.lock.json') }}
          restore-keys: ${{ runner.os }}-nuget-

      - name: Cake build
        run: dotnet tool restore && dotnet cake --verbosity=verbose --publish=true

  Linux:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout source
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Install dotnet
        uses: actions/setup-dotnet@v1.8.0
        with:
          dotnet-version: 5.0.202

      - name: Cache packages
        uses: actions/cache@v2.1.5
        with:
          path: ${{ env.NUGET_PACKAGES }}
          key: ${{ runner.os }}-nuget-${{ hashFiles('.config/dotnet-tools.json', '**/packages.lock.json') }}
          restore-keys: ${{ runner.os }}-nuget-

      - name: Cake build
        run: dotnet tool restore && dotnet cake --verbosity=verbose

  Mac:
    runs-on: macos-latest
    steps:
      - name: Checkout source
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Install dotnet
        uses: actions/setup-dotnet@v1.8.0
        with:
          dotnet-version: 5.0.202

      - name: Cache packages
        uses: actions/cache@v2.1.5
        with:
          path: ${{ env.NUGET_PACKAGES }}
          key: ${{ runner.os }}-nuget-${{ hashFiles('.config/dotnet-tools.json', '**/packages.lock.json') }}
          restore-keys: ${{ runner.os }}-nuget-

      - name: Cake build
        run: dotnet tool restore && dotnet cake --verbosity=verbose

  Windows:
    runs-on: windows-latest
    steps:
      - name: Checkout source
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Install dotnet
        uses: actions/setup-dotnet@v1.8.0
        with:
          dotnet-version: 5.0.202

      - name: Cache packages
        uses: actions/cache@v2.1.5
        with:
          path: ${{ env.NUGET_PACKAGES }}
          key: ${{ runner.os }}-nuget-${{ hashFiles('.config/dotnet-tools.json', '**/packages.lock.json') }}
          restore-keys: ${{ runner.os }}-nuget-

      - name: Cake build
        run: dotnet tool restore && dotnet cake --verbosity=verbose
