name: Build
on: [push, pull_request]

jobs:
  Docker:
    needs: [Linux, Mac, Windows]
    runs-on: ubuntu-18.04
    container: dockfool/cake-docker:latest
    steps:
    - name: Checkout source
      uses: actions/checkout@v1

    - name: Cake build
      run: cake --bootstrap && cake --verbosity=verbose --ispublisher=true
      env:
        NUGET_API_KEY: $
        NUGET_SOURCE: $

  Linux:
    runs-on: ubuntu-18.04
    steps:
    - name: Install .NET Core SDK
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 2.2.402

    - name: Checkout source
      uses: actions/checkout@v1

    - name: Cake build
      run: ./cake.sh --verbosity=verbose
      env:
        DOTNET_ROOT: /opt/hostedtoolcache/dncs/2.2.402/x64

  Mac:
    runs-on: macOS-10.14
    steps:
    - name: Install .NET Core SDK
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 2.2.402

    - name: Checkout source
      uses: actions/checkout@v1

    - name: Cake build
      run: ./cake.sh --verbosity=verbose
      env:
        DOTNET_ROOT: /Users/runner/hostedtoolcache/dncs/2.2.402/x64

  Windows:
    runs-on: windows-2019
    steps:
    - name: Install .NET Core SDK
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 2.2.402

    - name: Checkout source
      uses: actions/checkout@v1

    - name: Cake build
      shell: powershell
      run: ./cake.ps1 --verbosity=verbose
