name: ci
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: ${{ github.ref != 'refs/heads/main' }}

env:
  CAKE_SETTINGS_ENABLESCRIPTCACHE: true
  CAKE_SETTINGS_SHOWPROCESSCOMMANDLINE: true
  DOTNET_CLI_TELEMETRY_OPTOUT: true
  DOTNET_NOLOGO: true
  DOTNET_ROLL_FORWARD: Major
  NUGET_API_KEY: ${{ secrets.NUGET_API_KEY }}
  NUGET_PACKAGES: ${{ github.workspace }}/.nuget/packages

jobs:
  build-docker:
    needs: [ build-linux, build-mac, build-windows ]
    runs-on: ubuntu-latest
    container: dockfool/cake-docker:latest
    steps:
      - name: Checkout source
        uses: actions/checkout@v3.1.0
        with:
          fetch-depth: 0
          submodules: recursive

      - name: Cache packages
        uses: actions/cache@v3.0.11
        with:
          path: ${{ env.NUGET_PACKAGES }}
          key: ${{ runner.os }}-nuget-${{ hashFiles('.config/dotnet-tools.json', '**/packages.lock.json') }}
          restore-keys: ${{ runner.os }}-nuget-

      - name: Cake build
        id: cake-build
        run: dotnet tool restore && dotnet cake --verbosity=verbose --publish=true

      - name: Show outputs
        uses: actions/github-script@v6.3.3
        with:
          script: |
            // show outputs
            const outputs = ${{ steps.cake-build.outputs.build }};
            console.log(JSON.stringify(outputs, null, 2));

  build-linux:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout source
        uses: actions/checkout@v3.1.0
        with:
          fetch-depth: 0
          submodules: recursive

      - name: Install dotnet
        uses: actions/setup-dotnet@v3.0.3
        with:
          # renovate: datasource=dotnet depName=dotnet-sdk
          dotnet-version: 6.0.403

      - name: Cache packages
        uses: actions/cache@v3.0.11
        with:
          path: ${{ env.NUGET_PACKAGES }}
          key: ${{ runner.os }}-nuget-${{ hashFiles('.config/dotnet-tools.json', '**/packages.lock.json') }}
          restore-keys: ${{ runner.os }}-nuget-

      - name: Cake build
        id: cake-build
        run: dotnet tool restore && dotnet cake --verbosity=verbose

      - name: Show outputs
        uses: actions/github-script@v6.3.3
        with:
          script: |
            // show outputs
            const outputs = ${{ steps.cake-build.outputs.build }};
            console.log(JSON.stringify(outputs, null, 2));

  build-mac:
    runs-on: macos-latest
    steps:
      - name: Checkout source
        uses: actions/checkout@v3.1.0
        with:
          fetch-depth: 0
          submodules: recursive

      - name: Install dotnet
        uses: actions/setup-dotnet@v3.0.3
        with:
          # renovate: datasource=dotnet depName=dotnet-sdk
          dotnet-version: 6.0.403

      - name: Cache packages
        uses: actions/cache@v3.0.11
        with:
          path: ${{ env.NUGET_PACKAGES }}
          key: ${{ runner.os }}-nuget-${{ hashFiles('.config/dotnet-tools.json', '**/packages.lock.json') }}
          restore-keys: ${{ runner.os }}-nuget-

      - name: Cake build
        id: cake-build
        run: dotnet tool restore && dotnet cake --verbosity=verbose

      - name: Show outputs
        uses: actions/github-script@v6.3.3
        with:
          script: |
            // show outputs
            const outputs = ${{ steps.cake-build.outputs.build }};
            console.log(JSON.stringify(outputs, null, 2));

  build-windows:
    runs-on: windows-latest
    steps:
      - name: Checkout source
        uses: actions/checkout@v3.1.0
        with:
          fetch-depth: 0
          submodules: recursive

      - name: Install dotnet
        uses: actions/setup-dotnet@v3.0.3
        with:
          # renovate: datasource=dotnet depName=dotnet-sdk
          dotnet-version: 6.0.403

      - name: Cache packages
        uses: actions/cache@v3.0.11
        with:
          path: ${{ env.NUGET_PACKAGES }}
          key: ${{ runner.os }}-nuget-${{ hashFiles('.config/dotnet-tools.json', '**/packages.lock.json') }}
          restore-keys: ${{ runner.os }}-nuget-

      - name: Cake build
        id: cake-build
        run: dotnet tool restore && dotnet cake --verbosity=verbose

      - name: Show outputs
        uses: actions/github-script@v6.3.3
        with:
          script: |
            // show outputs
            const outputs = ${{ steps.cake-build.outputs.build }};
            console.log(JSON.stringify(outputs, null, 2));
