name: ci
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
  workflow_dispatch:

env:
  CAKE_SETTINGS_SHOWPROCESSCOMMANDLINE: true
  DOTNET_CLI_TELEMETRY_OPTOUT: true
  DOTNET_NOLOGO: true
  DOTNET_ROLL_FORWARD: Major
  NUGET_API_KEY: ${{ secrets.NUGET_API_KEY }}
  NUGET_PACKAGES: ${{ github.workspace }}/.nuget/packages

jobs:
  build-docker:
    needs: [ build-linux, build-mac, build-windows ]
    runs-on: ubuntu-latest
    container: dockfool/cake-docker:latest
    steps:
      - name: Checkout source
        uses: actions/checkout@v2.4.0
        with:
          fetch-depth: 0
          submodules: true

      - name: Cache packages
        uses: actions/cache@v2.1.7
        with:
          path: ${{ env.NUGET_PACKAGES }}
          key: ${{ runner.os }}-nuget-${{ hashFiles('.config/dotnet-tools.json', '**/packages.lock.json') }}
          restore-keys: ${{ runner.os }}-nuget-

      - name: Cake build
        run: dotnet tool restore && dotnet cake --verbosity=verbose --publish=true

  build-linux:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout source
        uses: actions/checkout@v2.4.0
        with:
          fetch-depth: 0
          submodules: true

      - name: Install dotnet
        uses: actions/setup-dotnet@v1.9.0
        with:
          dotnet-version: 6.0.100

      - name: Cache packages
        uses: actions/cache@v2.1.7
        with:
          path: ${{ env.NUGET_PACKAGES }}
          key: ${{ runner.os }}-nuget-${{ hashFiles('.config/dotnet-tools.json', '**/packages.lock.json') }}
          restore-keys: ${{ runner.os }}-nuget-

      - name: Cake build
        run: dotnet tool restore && dotnet cake --verbosity=verbose

  build-mac:
    runs-on: macos-latest
    steps:
      - name: Checkout source
        uses: actions/checkout@v2.4.0
        with:
          fetch-depth: 0
          submodules: true

      - name: Install dotnet
        uses: actions/setup-dotnet@v1.9.0
        with:
          dotnet-version: 6.0.100

      - name: Cache packages
        uses: actions/cache@v2.1.7
        with:
          path: ${{ env.NUGET_PACKAGES }}
          key: ${{ runner.os }}-nuget-${{ hashFiles('.config/dotnet-tools.json', '**/packages.lock.json') }}
          restore-keys: ${{ runner.os }}-nuget-

      - name: Cake build
        run: dotnet tool restore && dotnet cake --verbosity=verbose

  build-windows:
    runs-on: windows-latest
    steps:
      - name: Checkout source
        uses: actions/checkout@v2.4.0
        with:
          fetch-depth: 0
          submodules: true

      - name: Install dotnet
        uses: actions/setup-dotnet@v1.9.0
        with:
          dotnet-version: 6.0.100

      - name: Cache packages
        uses: actions/cache@v2.1.7
        with:
          path: ${{ env.NUGET_PACKAGES }}
          key: ${{ runner.os }}-nuget-${{ hashFiles('.config/dotnet-tools.json', '**/packages.lock.json') }}
          restore-keys: ${{ runner.os }}-nuget-

      - name: Cake build
        run: dotnet tool restore && dotnet cake --verbosity=verbose
