name: ci
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

env:
  CAKE_SETTINGS_SHOWPROCESSCOMMANDLINE: true
  DOTNET_CLI_TELEMETRY_OPTOUT: true
  DOTNET_NOLOGO: true
  DOTNET_ROLL_FORWARD: Major
  NUGET_API_KEY: ${{ secrets.NUGET_API_KEY }}
  NUGET_PACKAGES: ${{ github.workspace }}/.nuget/packages

jobs:
  build-docker:
    needs: [ build-linux, build-mac, build-windows ]
    runs-on: ubuntu-latest
    container: dockfool/cake-docker:latest
    steps:
      - name: Checkout source
        uses: actions/checkout@v3.0.0
        with:
          fetch-depth: 0
          submodules: true

      - name: Cache packages
        uses: actions/cache@v3.0.2
        with:
          path: ${{ env.NUGET_PACKAGES }}
          key: ${{ runner.os }}-nuget-${{ hashFiles('.config/dotnet-tools.json', '**/packages.lock.json') }}
          restore-keys: ${{ runner.os }}-nuget-

      - name: Cake build
        id: cake-build
        run: dotnet tool restore && dotnet cake --verbosity=verbose --publish=true

      - name: Show outputs
        run: |
          # steps.cake-build.outputs.build
          echo "${{ toJson(fromJson(steps.cake-build.outputs.build)) }}"

  build-linux:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout source
        uses: actions/checkout@v3.0.0
        with:
          fetch-depth: 0
          submodules: true

      - name: Install dotnet
        uses: actions/setup-dotnet@v2.0.0
        with:
          # renovate: datasource=docker depName=dotnet-sdk packageName=mcr.microsoft.com/dotnet/sdk
          dotnet-version: 6.0.202

      - name: Cache packages
        uses: actions/cache@v3.0.2
        with:
          path: ${{ env.NUGET_PACKAGES }}
          key: ${{ runner.os }}-nuget-${{ hashFiles('.config/dotnet-tools.json', '**/packages.lock.json') }}
          restore-keys: ${{ runner.os }}-nuget-

      - name: Cake build
        id: cake-build
        run: dotnet tool restore && dotnet cake --verbosity=verbose

      - name: Show outputs
        run: |
          # steps.cake-build.outputs.build
          echo "${{ toJson(fromJson(steps.cake-build.outputs.build)) }}"

  build-mac:
    runs-on: macos-latest
    steps:
      - name: Checkout source
        uses: actions/checkout@v3.0.0
        with:
          fetch-depth: 0
          submodules: true

      - name: Install dotnet
        uses: actions/setup-dotnet@v2.0.0
        with:
          # renovate: datasource=docker depName=dotnet-sdk packageName=mcr.microsoft.com/dotnet/sdk
          dotnet-version: 6.0.202

      - name: Cache packages
        uses: actions/cache@v3.0.2
        with:
          path: ${{ env.NUGET_PACKAGES }}
          key: ${{ runner.os }}-nuget-${{ hashFiles('.config/dotnet-tools.json', '**/packages.lock.json') }}
          restore-keys: ${{ runner.os }}-nuget-

      - name: Cake build
        id: cake-build
        run: dotnet tool restore && dotnet cake --verbosity=verbose

      - name: Show outputs
        run: |
          # steps.cake-build.outputs.build
          echo "${{ toJson(fromJson(steps.cake-build.outputs.build)) }}"

  build-windows:
    runs-on: windows-latest
    steps:
      - name: Checkout source
        uses: actions/checkout@v3.0.0
        with:
          fetch-depth: 0
          submodules: true

      - name: Install dotnet
        uses: actions/setup-dotnet@v2.0.0
        with:
          # renovate: datasource=docker depName=dotnet-sdk packageName=mcr.microsoft.com/dotnet/sdk
          dotnet-version: 6.0.202

      - name: Cache packages
        uses: actions/cache@v3.0.2
        with:
          path: ${{ env.NUGET_PACKAGES }}
          key: ${{ runner.os }}-nuget-${{ hashFiles('.config/dotnet-tools.json', '**/packages.lock.json') }}
          restore-keys: ${{ runner.os }}-nuget-

      - name: Cake build
        id: cake-build
        run: dotnet tool restore && dotnet cake --verbosity=verbose

      - name: Show outputs
        run: |
          # steps.cake-build.outputs.build
          echo "${{ toJson(fromJson(steps.cake-build.outputs.build)) }}"
