name: Dependabot
on:
  schedule:
    - cron: '0 5 * * *'
  workflow_dispatch:

jobs:
  Cake:
    runs-on: ubuntu-latest
    steps:
      - name: Check dependencies
        uses: nils-org/dependabot-cake-action@v1.1.0
        with:
          directory: /
